model:
  type: pyramid
  depth: 272
  alpha: 200
  bottleneck: True
dataset: permutated_cifar100
aug: fa_reduced_cifar10
cutout: 16
batch: 64
epoch: 100
lr: 0.05
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.00005